# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce41af72b027da8331853b7e99f2e86ab26eb50f58c7d9f25b54e332b3ebee4007b915e9d4aad4ba1e5f376db68b7f7477e6d90304fb285e9c2d54fd7f18e6c1

test:
  secret_key_base: bd10294baa99918ca49eb747199519fec0d1f3b580e7b68a43f16b62f90fd96c7185d53dd7272e1d2cbb8e3f3d574f353d0cb2bb6c209c16c7215486a2a92a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
